name: Compilar Ejecutables MANAAplot

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar en ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependencias de Linux (Solo Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y python3-tk

    - name: Instalar dependencias de Python
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib pyinstaller

    - name: Generar y parchear archivo .spec (Límite de Recursividad)
      run: |
        pyi-makespec --noconsole --onefile --hidden-import PIL._tkinter_finder maanaplot.py
        python -c "import sys; lines = open('maanaplot.spec').readlines(); lines.insert(0, 'import sys\nsys.setrecursionlimit(5000)\n'); open('maanaplot.spec', 'w').writelines(lines)"

    - name: Compilar con PyInstaller
      run: pyinstaller maanaplot.spec

    - name: Subir los ejecutables generados
      uses: actions/upload-artifact@v4
      with:
        name: MANAAplot-Ejecutable-${{ runner.os }}
        path: dist/*
